### ISSUE TITLE
Won't this only work on managed chromebooks. i.e its not possible on macs or windows

### ISSUE THREAD

**Issue by JakeA1234** [xNasuni/google-forms-unlocker#3]
I know you have steps to bypass the form only working on chromebooks, but not only that I belive it only works on managed chromebooks so how do you replicate this on a mac? please let me know asap

**Comment by xNasuni** [comment]
as long as you have your school account on your personal computer you can do locked forms on your personal computer.
you can install a browser like google OR firefox on macOS to install a userscript manager and useragent spoofer.

that's all you'd need to do locked forms outside of a managed chromebook and not even on a chromebook.

if you need more help feel free to ask.

**Comment by JakeA1234** [comment]
do i need to have sync on or do I just need to be logged into google. I ask this because I have a sync on then Hapara is installed where the teacher can see my screen. But that is not a massive issue cause she assumes that we are locked down. Also is there any way that a teacher can see I am doing this. Lastly is there any way I can test to see if it works? I will close issue once responded. Thanks

**Comment by xNasuni** [comment]
you just need to be logged into google, you don't need to sync to do forms, it's just an account thing.

I'd recommend NOT making a profile specifically for school email because then sync will install extensions and the profile will have school policies and stuff, what I'd recommend is login to your school email alongside your actual primary account through the account selector.
![image](https://github.com/user-attachments/assets/e137e0fe-45fb-4ed6-b1d0-afa2e5d5e3d4)

after you have your school account there, you wont need to sync to use it, then you can go to google classroom for example on that school account, then find the form and go to it, once you go there you will be able to do the form without actually being in locked mode.

in response to "Lastly is there any way I can test to see if it works?", you can create a form yourself and turn on locked quiz mode, and try accessing it with the script, and you can see that you can do it.

the only issue is that if you close the tab and reopen it, the teacher can see that you opened it multiple times, this already happens even without the script if you do a locked quiz normally when you exit the quiz and reopen it, it tells the teacher it was opened more than once but this script doens't stop that.

if you finish it without closing the tab then it wont say anything.

**Comment by JakeA1234** [comment]
you are so helpful, but I am confused as to which or wat tab you are referring to. from my understanding I can take the test and open tabs for chatgpt or google but your saying I just shouldn't close them until after the test? please let me know if this is the case.

**Comment by xNasuni** [comment]
the tab that you can't close is the actual form tab, because when you do this, the next time you open the quiz the teacher will see that you opened it more than once.

like, if I was taking an actual test on my school chromebook and I pressed Cloze Quiz button at the bottom, then reopened the locked quiz then submitted the quiz, it'll tell the teacher I opened it more than once. if you close the tab with this bypass it'll also say that, that's the only risk.

**Comment by JakeA1234** [comment]
ok so everything is fine that I do I just cant close the form/test and re open it. I should close it at the end. I don't believe you can make a locked test unless you are like a Google enterprise person/teacher.

**Comment by xNasuni** [comment]
go to https://forms.new/, and then go to the settings, and if you turn on this is a quiz, you will see an option here to make a locked test. this option is only limited to accounts connected to organizations, not just teachers.

#### (you will see an option here, it doesn't show up for me because I'm not on my school account rn but you will see it)
![image](https://github.com/user-attachments/assets/51519fcf-5fa3-4f5d-b20e-46e42d76b57c)

**Comment by JakeA1234** [comment]
you are the best. One day I hope to achieve your skills. Have a great day!

**Comment by shubhbha0608** [comment]
Hi there, I have a test today I am kinda worried. I had downloaded the script manager and the user agent changer and everything had worked. I followed your steps and it had worked everyday for more than two weeks, until yesterday, the day before my test.

![Image](https://github.com/user-attachments/assets/33a15fc4-ae18-4abb-804c-8bccb58dd7d9) It keeps giving me this

**Comment by shubhbha0608** [comment]
I also have the user agent script correct

**Comment by xNasuni** [comment]
the thing it's saying means my script isnt running, try using another userscript manager maybe?

i don't know why'd it stop randomly like that
